version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
  - dependency-name: junit:junit
    versions:
    - 4.13.1
- package-ecosystem: gradle
  directory: "/gradleinclude"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
