language: java
after_success:
  - bash codecov.bash
env:
  matrix:
    secure: s1CBU0ELTvP+1n61SaTqp9a8nmTv9B+C6hbIg9gt9QBkS129T14s8PYf3Gr5pyjDsyvF8jspzep5Gh8gYT+2GIexR0K+WDqn2FAWfW+i8/YhvI4s57XTw2xOJ2kWi/LhZZ+6LiS0b4A9wf1XVtuIVOda9/cmW76+hmHmKKadeKIrwlaZcRYJv/GV2nmwzvJEYOU7NVNGJoAFdT7roY0Y68sVQI4Q1i5v7uG3mYoxDG2v+dsdZwsaMkJu4VvisVrMfNN0A62E9iGQuFMh0ughKaTJzfozLIviyyVPcvgTuxdSXeNW5BZQYAcKVjCxy0Eds5UZFx/O6HrwcoFhgltDe4HhiGXGwUtc1wssZCT+I7pDYbKtDFNi7x/Vyn2t2CxVvocZlQ7hyD+/TFvpf2KJBNSCy8k5Ys5bgg9mgZWCRaxqbpC6RLFDTnWgxp/BOcogVKDromtJcpR20fvKnjpNec1kR2BVELtAh18yvpFW4OhjKd6g9g7RqcrhT/8xKpCmugI2hk/H+/VnVTCJrtM1w9MdmMvQMOqrVAbgL/s7MX0w+OlRZCivZsNkvUvxdWxUJgNqomtYldFGR75ByGYmRDIKyV+TXreuSV0JlwkYFkgx231X0/xt9TCXQEDSnzsk+ZK4HdzfsaAyjnZvJldVRrU/hKm3eN3v0Nk3k7R9cL8=
