package com.wtanaka.ciconfiggen

import com.google.protobuf.TextFormat
import com.wtanaka.ciconfiggen.ConfigProto.Configuration
import java.io.File

/**
 * Main entrypoint for CLI.
 */
fun main(args: Array<String>) {
    val config = File(".ciconfiggen.config")
        .inputStream().reader(Charsets.UTF_8).use {
            val config = Configuration.newBuilder()
            TextFormat.getParser().merge(it, config)
            config
        }
    File(".circleci/").mkdir()
    listOf(
        Triple(".travis.yml", defaultYaml(), travisConfig(config.build())),
        Triple(".circleci/config.yml", defaultYaml(),
            circleConfig(config.build()))
    ).forEach { triple ->
        File(triple.first).outputStream().writer(Charsets.UTF_8).use {
            it.write(
                "# This file was generated by" +
                    " https://github.com/wtanaka/ciconfiggen\n")
            it.write("# DO NOT EDIT\n")
            it.write(config?.let {
                triple.second.dump(triple.third)
            })
        }
    }
}
