package com.wtanaka.ciconfiggen

import com.google.protobuf.TextFormat
import com.wtanaka.ciconfiggen.ConfigProto.Configuration
import com.wtanaka.ciconfiggen.ConfigProto.Configuration.CiService
import com.wtanaka.ciconfiggen.ConfigProto.Configuration.Environment
import com.wtanaka.ciconfiggen.ConfigProto.Configuration.EnvironmentNameValuePair
import com.wtanaka.ciconfiggen.ConfigProto.Configuration.EnvironmentVariableAxis
import com.wtanaka.ciconfiggen.ConfigProto.Configuration.Suppression
import java.io.File

fun envMatrixTyped(
    config: Sequence<EnvironmentVariableAxis>
): Sequence<Environment> {
    val first = config.firstOrNull()
    return when (first) {
        null -> emptySequence()
        else -> {
            val restSeq = envMatrixTyped(config.drop(1))
            first.valueList.asSequence().map { value ->
                val thisEnv = EnvironmentNameValuePair
                    .newBuilder()
                    .setName(first.name)
                    .setValue(value)

                when (restSeq.firstOrNull()) {
                    null -> sequenceOf(
                        Environment.newBuilder().addPair(thisEnv).build())
                    else -> restSeq.map {
                        it.toBuilder().addPair(thisEnv).build()
                    }
                }
            }.flatten()
        }
    }
}

private fun Environment.matches(suppression: Suppression): Boolean =
    this.pairList.toSet().let { envSet ->
        suppression.envList.all { it in envSet }
    }

fun Sequence<Environment>.suppress(suppression: Suppression) = this.filter {
    !it.matches(suppression)
}

fun Environment.shellString(): String =
    this.pairList.map { "${it.name}=${it.value}" }.joinToString(" ")

fun envMatrix(
    config: Sequence<EnvironmentVariableAxis>
): Sequence<String> {
    val first = config.firstOrNull()
    return when (first) {
        null -> emptySequence()
        else -> {
            val restSeq = envMatrix(config.drop(1))
            first.valueList.asSequence().map { value ->
                val thisEnv = "${first.name}=$value"
                when (restSeq.firstOrNull()) {
                    null -> sequenceOf(thisEnv)
                    else -> restSeq.map { "$it $thisEnv" }
                }
            }.flatten()
        }
    }
}

fun envMatrix(
    config: Configuration, service: CiService
): Sequence<Environment> = config
    .envAxisList
    .asSequence()
    .filterNotNull()
    .let { envMatrixTyped(it) }
    .let { sequenceOfEnv ->
        config.suppressList
            .filter { service == it.service }
            .fold(sequenceOfEnv) { envSeq, suppression ->
                envSeq.suppress(suppression)
            }
    }

fun main(args: Array<String>) {
    val config = File(".ciconfiggen.config")
        .inputStream().reader(Charsets.UTF_8).use {
            val config = Configuration.newBuilder()
            TextFormat.getParser().merge(it, config)
            config
        }
    File(".circleci/").mkdir()
    listOf(
        Triple(".travis.yml", defaultYaml(), travisConfig(config.build())),
        Triple(".circleci/config.yml", defaultYaml(),
            circleConfig(config.build()))
    ).forEach { triple ->
        File(triple.first).outputStream().writer(Charsets.UTF_8).use {
            it.write(
                "# This file was generated by https://github.com/wtanaka/ciconfiggen\n")
            it.write("# DO NOT EDIT\n")
            it.write(config?.let {
                triple.second.dump(triple.third)
            })
        }
    }
}
